package com.bumbatech.bumbalearning.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AchievementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAchievementAllPropertiesEquals(Achievement expected, Achievement actual) {
        assertAchievementAutoGeneratedPropertiesEquals(expected, actual);
        assertAchievementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAchievementAllUpdatablePropertiesEquals(Achievement expected, Achievement actual) {
        assertAchievementUpdatableFieldsEquals(expected, actual);
        assertAchievementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAchievementAutoGeneratedPropertiesEquals(Achievement expected, Achievement actual) {
        assertThat(actual)
            .as("Verify Achievement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAchievementUpdatableFieldsEquals(Achievement expected, Achievement actual) {
        assertThat(actual)
            .as("Verify Achievement relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getIconUrl()).as("check iconUrl").isEqualTo(expected.getIconUrl()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCriteria()).as("check criteria").isEqualTo(expected.getCriteria()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAchievementUpdatableRelationshipsEquals(Achievement expected, Achievement actual) {
        // empty method
    }
}
