package com.bumbatech.bumbalearning.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AttemptAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttemptAllPropertiesEquals(Attempt expected, Attempt actual) {
        assertAttemptAutoGeneratedPropertiesEquals(expected, actual);
        assertAttemptAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttemptAllUpdatablePropertiesEquals(Attempt expected, Attempt actual) {
        assertAttemptUpdatableFieldsEquals(expected, actual);
        assertAttemptUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttemptAutoGeneratedPropertiesEquals(Attempt expected, Attempt actual) {
        assertThat(actual)
            .as("Verify Attempt auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttemptUpdatableFieldsEquals(Attempt expected, Attempt actual) {
        assertThat(actual)
            .as("Verify Attempt relevant properties")
            .satisfies(a -> assertThat(a.getIsCorrect()).as("check isCorrect").isEqualTo(expected.getIsCorrect()))
            .satisfies(a -> assertThat(a.getTimeSpentSeconds()).as("check timeSpentSeconds").isEqualTo(expected.getTimeSpentSeconds()))
            .satisfies(a -> assertThat(a.getAttemptedAt()).as("check attemptedAt").isEqualTo(expected.getAttemptedAt()))
            .satisfies(a -> assertThat(a.getAnswer()).as("check answer").isEqualTo(expected.getAnswer()))
            .satisfies(a -> assertThat(a.getMetadata()).as("check metadata").isEqualTo(expected.getMetadata()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttemptUpdatableRelationshipsEquals(Attempt expected, Attempt actual) {
        assertThat(actual)
            .as("Verify Attempt relationships")
            .satisfies(a -> assertThat(a.getQuestion()).as("check question").isEqualTo(expected.getQuestion()))
            .satisfies(a -> assertThat(a.getLesson()).as("check lesson").isEqualTo(expected.getLesson()));
    }
}
