package com.bumbatech.bumbalearning.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClassMemberAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassMemberAllPropertiesEquals(ClassMember expected, ClassMember actual) {
        assertClassMemberAutoGeneratedPropertiesEquals(expected, actual);
        assertClassMemberAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassMemberAllUpdatablePropertiesEquals(ClassMember expected, ClassMember actual) {
        assertClassMemberUpdatableFieldsEquals(expected, actual);
        assertClassMemberUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassMemberAutoGeneratedPropertiesEquals(ClassMember expected, ClassMember actual) {
        assertThat(actual)
            .as("Verify ClassMember auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassMemberUpdatableFieldsEquals(ClassMember expected, ClassMember actual) {
        assertThat(actual)
            .as("Verify ClassMember relevant properties")
            .satisfies(a -> assertThat(a.getEnrolledAt()).as("check enrolledAt").isEqualTo(expected.getEnrolledAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassMemberUpdatableRelationshipsEquals(ClassMember expected, ClassMember actual) {
        assertThat(actual)
            .as("Verify ClassMember relationships")
            .satisfies(a -> assertThat(a.getClassRoom()).as("check classRoom").isEqualTo(expected.getClassRoom()));
    }
}
