package com.bumbatech.bumbalearning.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClassRoomAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassRoomAllPropertiesEquals(ClassRoom expected, ClassRoom actual) {
        assertClassRoomAutoGeneratedPropertiesEquals(expected, actual);
        assertClassRoomAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassRoomAllUpdatablePropertiesEquals(ClassRoom expected, ClassRoom actual) {
        assertClassRoomUpdatableFieldsEquals(expected, actual);
        assertClassRoomUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassRoomAutoGeneratedPropertiesEquals(ClassRoom expected, ClassRoom actual) {
        assertThat(actual)
            .as("Verify ClassRoom auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassRoomUpdatableFieldsEquals(ClassRoom expected, ClassRoom actual) {
        assertThat(actual)
            .as("Verify ClassRoom relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getLanguage()).as("check language").isEqualTo(expected.getLanguage()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassRoomUpdatableRelationshipsEquals(ClassRoom expected, ClassRoom actual) {
        // empty method
    }
}
