package com.bumbatech.bumbalearning.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LessonAssignmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLessonAssignmentAllPropertiesEquals(LessonAssignment expected, LessonAssignment actual) {
        assertLessonAssignmentAutoGeneratedPropertiesEquals(expected, actual);
        assertLessonAssignmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLessonAssignmentAllUpdatablePropertiesEquals(LessonAssignment expected, LessonAssignment actual) {
        assertLessonAssignmentUpdatableFieldsEquals(expected, actual);
        assertLessonAssignmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLessonAssignmentAutoGeneratedPropertiesEquals(LessonAssignment expected, LessonAssignment actual) {
        assertThat(actual)
            .as("Verify LessonAssignment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLessonAssignmentUpdatableFieldsEquals(LessonAssignment expected, LessonAssignment actual) {
        assertThat(actual)
            .as("Verify LessonAssignment relevant properties")
            .satisfies(a -> assertThat(a.getAssignedAt()).as("check assignedAt").isEqualTo(expected.getAssignedAt()))
            .satisfies(a -> assertThat(a.getDueDate()).as("check dueDate").isEqualTo(expected.getDueDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLessonAssignmentUpdatableRelationshipsEquals(LessonAssignment expected, LessonAssignment actual) {
        assertThat(actual)
            .as("Verify LessonAssignment relationships")
            .satisfies(a -> assertThat(a.getClassRoom()).as("check classRoom").isEqualTo(expected.getClassRoom()))
            .satisfies(a -> assertThat(a.getLesson()).as("check lesson").isEqualTo(expected.getLesson()));
    }
}
