package com.bumbatech.bumbalearning.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LessonQuestionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLessonQuestionAllPropertiesEquals(LessonQuestion expected, LessonQuestion actual) {
        assertLessonQuestionAutoGeneratedPropertiesEquals(expected, actual);
        assertLessonQuestionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLessonQuestionAllUpdatablePropertiesEquals(LessonQuestion expected, LessonQuestion actual) {
        assertLessonQuestionUpdatableFieldsEquals(expected, actual);
        assertLessonQuestionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLessonQuestionAutoGeneratedPropertiesEquals(LessonQuestion expected, LessonQuestion actual) {
        assertThat(actual)
            .as("Verify LessonQuestion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLessonQuestionUpdatableFieldsEquals(LessonQuestion expected, LessonQuestion actual) {
        assertThat(actual)
            .as("Verify LessonQuestion relevant properties")
            .satisfies(a -> assertThat(a.getOrderIndex()).as("check orderIndex").isEqualTo(expected.getOrderIndex()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLessonQuestionUpdatableRelationshipsEquals(LessonQuestion expected, LessonQuestion actual) {
        assertThat(actual)
            .as("Verify LessonQuestion relationships")
            .satisfies(a -> assertThat(a.getLesson()).as("check lesson").isEqualTo(expected.getLesson()))
            .satisfies(a -> assertThat(a.getQuestion()).as("check question").isEqualTo(expected.getQuestion()));
    }
}
