package com.bumbatech.bumbalearning.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RecommendationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecommendationAllPropertiesEquals(Recommendation expected, Recommendation actual) {
        assertRecommendationAutoGeneratedPropertiesEquals(expected, actual);
        assertRecommendationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecommendationAllUpdatablePropertiesEquals(Recommendation expected, Recommendation actual) {
        assertRecommendationUpdatableFieldsEquals(expected, actual);
        assertRecommendationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecommendationAutoGeneratedPropertiesEquals(Recommendation expected, Recommendation actual) {
        assertThat(actual)
            .as("Verify Recommendation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecommendationUpdatableFieldsEquals(Recommendation expected, Recommendation actual) {
        assertThat(actual)
            .as("Verify Recommendation relevant properties")
            .satisfies(a -> assertThat(a.getRecommendedAt()).as("check recommendedAt").isEqualTo(expected.getRecommendedAt()))
            .satisfies(a -> assertThat(a.getWasCompleted()).as("check wasCompleted").isEqualTo(expected.getWasCompleted()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecommendationUpdatableRelationshipsEquals(Recommendation expected, Recommendation actual) {
        assertThat(actual)
            .as("Verify Recommendation relationships")
            .satisfies(a -> assertThat(a.getLesson()).as("check lesson").isEqualTo(expected.getLesson()));
    }
}
