package com.bumbatech.bumbalearning.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StudentLessonProgressAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentLessonProgressAllPropertiesEquals(StudentLessonProgress expected, StudentLessonProgress actual) {
        assertStudentLessonProgressAutoGeneratedPropertiesEquals(expected, actual);
        assertStudentLessonProgressAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentLessonProgressAllUpdatablePropertiesEquals(
        StudentLessonProgress expected,
        StudentLessonProgress actual
    ) {
        assertStudentLessonProgressUpdatableFieldsEquals(expected, actual);
        assertStudentLessonProgressUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentLessonProgressAutoGeneratedPropertiesEquals(
        StudentLessonProgress expected,
        StudentLessonProgress actual
    ) {
        assertThat(actual)
            .as("Verify StudentLessonProgress auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentLessonProgressUpdatableFieldsEquals(StudentLessonProgress expected, StudentLessonProgress actual) {
        assertThat(actual)
            .as("Verify StudentLessonProgress relevant properties")
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getScore()).as("check score").isEqualTo(expected.getScore()))
            .satisfies(a -> assertThat(a.getXpEarned()).as("check xpEarned").isEqualTo(expected.getXpEarned()))
            .satisfies(a -> assertThat(a.getCompletedAt()).as("check completedAt").isEqualTo(expected.getCompletedAt()))
            .satisfies(a -> assertThat(a.getIsLate()).as("check isLate").isEqualTo(expected.getIsLate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentLessonProgressUpdatableRelationshipsEquals(
        StudentLessonProgress expected,
        StudentLessonProgress actual
    ) {
        assertThat(actual)
            .as("Verify StudentLessonProgress relationships")
            .satisfies(a -> assertThat(a.getLesson()).as("check lesson").isEqualTo(expected.getLesson()))
            .satisfies(a -> assertThat(a.getAssignment()).as("check assignment").isEqualTo(expected.getAssignment()));
    }
}
