package com.bumbatech.bumbalearning.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TopicAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTopicAllPropertiesEquals(Topic expected, Topic actual) {
        assertTopicAutoGeneratedPropertiesEquals(expected, actual);
        assertTopicAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTopicAllUpdatablePropertiesEquals(Topic expected, Topic actual) {
        assertTopicUpdatableFieldsEquals(expected, actual);
        assertTopicUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTopicAutoGeneratedPropertiesEquals(Topic expected, Topic actual) {
        assertThat(actual)
            .as("Verify Topic auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTopicUpdatableFieldsEquals(Topic expected, Topic actual) {
        assertThat(actual)
            .as("Verify Topic relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getLanguage()).as("check language").isEqualTo(expected.getLanguage()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTopicUpdatableRelationshipsEquals(Topic expected, Topic actual) {
        // empty method
    }
}
