package com.bumbatech.bumbalearning.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserProfileAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserProfileAllPropertiesEquals(UserProfile expected, UserProfile actual) {
        assertUserProfileAutoGeneratedPropertiesEquals(expected, actual);
        assertUserProfileAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserProfileAllUpdatablePropertiesEquals(UserProfile expected, UserProfile actual) {
        assertUserProfileUpdatableFieldsEquals(expected, actual);
        assertUserProfileUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserProfileAutoGeneratedPropertiesEquals(UserProfile expected, UserProfile actual) {
        assertThat(actual)
            .as("Verify UserProfile auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserProfileUpdatableFieldsEquals(UserProfile expected, UserProfile actual) {
        assertThat(actual)
            .as("Verify UserProfile relevant properties")
            .satisfies(a -> assertThat(a.getMunicipalityCode()).as("check municipalityCode").isEqualTo(expected.getMunicipalityCode()))
            .satisfies(a -> assertThat(a.getCurrentLevel()).as("check currentLevel").isEqualTo(expected.getCurrentLevel()))
            .satisfies(a -> assertThat(a.getTotalXp()).as("check totalXp").isEqualTo(expected.getTotalXp()))
            .satisfies(a -> assertThat(a.getCurrentStreak()).as("check currentStreak").isEqualTo(expected.getCurrentStreak()))
            .satisfies(a -> assertThat(a.getDailyGoalXp()).as("check dailyGoalXp").isEqualTo(expected.getDailyGoalXp()))
            .satisfies(a -> assertThat(a.getLastActivityDate()).as("check lastActivityDate").isEqualTo(expected.getLastActivityDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserProfileUpdatableRelationshipsEquals(UserProfile expected, UserProfile actual) {
        // empty method
    }
}
