package com.bumbatech.bumbalearning.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserAchievementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAchievementAllPropertiesEquals(UserAchievement expected, UserAchievement actual) {
        assertUserAchievementAutoGeneratedPropertiesEquals(expected, actual);
        assertUserAchievementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAchievementAllUpdatablePropertiesEquals(UserAchievement expected, UserAchievement actual) {
        assertUserAchievementUpdatableFieldsEquals(expected, actual);
        assertUserAchievementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAchievementAutoGeneratedPropertiesEquals(UserAchievement expected, UserAchievement actual) {
        assertThat(actual)
            .as("Verify UserAchievement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAchievementUpdatableFieldsEquals(UserAchievement expected, UserAchievement actual) {
        assertThat(actual)
            .as("Verify UserAchievement relevant properties")
            .satisfies(a -> assertThat(a.getUnlockedAt()).as("check unlockedAt").isEqualTo(expected.getUnlockedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAchievementUpdatableRelationshipsEquals(UserAchievement expected, UserAchievement actual) {
        assertThat(actual)
            .as("Verify UserAchievement relationships")
            .satisfies(a -> assertThat(a.getAchievement()).as("check achievement").isEqualTo(expected.getAchievement()));
    }
}
